#!/bin/sh
# Hook: valida formato "<version> - descripcion"
# Instalar: git config core.hooksPath .githooks
msg=$(cat "$1")
if ! echo "$msg" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+ - .+'; then
  echo "Commit invalido. Usa: <MAJOR>.<MINOR>.<PATCH> - descripcion"
  echo "Ej: 1.0.1 - bug fix en backend"
  exit 1
fi
